'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type KiAlertCustomEvent } from "@kimen/elements";
import type { Components } from "@kimen/elements/components";
import { KiAlert as KiAlertElement, defineCustomElement as defineKiAlert } from "@kimen/elements/components/ki-alert.js";

export type KiAlertEvents = { onKiDismiss: EventName<KiAlertCustomEvent<null>> };

export const KiAlert: StencilReactComponent<KiAlertElement, KiAlertEvents, Components.KiAlert> = /*@__PURE__*/ createComponent<KiAlertElement, KiAlertEvents, Components.KiAlert>({
    tagName: 'ki-alert',
    elementClass: KiAlertElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onKiDismiss: 'ki-dismiss' } as KiAlertEvents,
    defineCustomElement: defineKiAlert
});
