'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiAvatar as KiAvatarElement, defineCustomElement as defineKiAvatar } from "@kimen/elements/components/ki-avatar.js";

export type KiAvatarEvents = NonNullable<unknown>;

export const KiAvatar: StencilReactComponent<KiAvatarElement, KiAvatarEvents, Components.KiAvatar> = /*@__PURE__*/ createComponent<KiAvatarElement, KiAvatarEvents, Components.KiAvatar>({
    tagName: 'ki-avatar',
    elementClass: KiAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiAvatarEvents,
    defineCustomElement: defineKiAvatar
});
