'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiAvatarGroup as KiAvatarGroupElement, defineCustomElement as defineKiAvatarGroup } from "@kimen/elements/components/ki-avatar-group.js";

export type KiAvatarGroupEvents = NonNullable<unknown>;

export const KiAvatarGroup: StencilReactComponent<KiAvatarGroupElement, KiAvatarGroupEvents, Components.KiAvatarGroup> = /*@__PURE__*/ createComponent<KiAvatarGroupElement, KiAvatarGroupEvents, Components.KiAvatarGroup>({
    tagName: 'ki-avatar-group',
    elementClass: KiAvatarGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiAvatarGroupEvents,
    defineCustomElement: defineKiAvatarGroup
});
