'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiBadge as KiBadgeElement, defineCustomElement as defineKiBadge } from "@kimen/elements/components/ki-badge.js";

export type KiBadgeEvents = NonNullable<unknown>;

export const KiBadge: StencilReactComponent<KiBadgeElement, KiBadgeEvents, Components.KiBadge> = /*@__PURE__*/ createComponent<KiBadgeElement, KiBadgeEvents, Components.KiBadge>({
    tagName: 'ki-badge',
    elementClass: KiBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiBadgeEvents,
    defineCustomElement: defineKiBadge
});
