'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiButton as KiButtonElement, defineCustomElement as defineKiButton } from "@kimen/elements/components/ki-button.js";

export type KiButtonEvents = NonNullable<unknown>;

export const KiButton: StencilReactComponent<KiButtonElement, KiButtonEvents, Components.KiButton> = /*@__PURE__*/ createComponent<KiButtonElement, KiButtonEvents, Components.KiButton>({
    tagName: 'ki-button',
    elementClass: KiButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiButtonEvents,
    defineCustomElement: defineKiButton
});
