'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiCheckbox as KiCheckboxElement, defineCustomElement as defineKiCheckbox } from "@kimen/elements/components/ki-checkbox.js";

export type KiCheckboxEvents = NonNullable<unknown>;

export const KiCheckbox: StencilReactComponent<KiCheckboxElement, KiCheckboxEvents, Components.KiCheckbox> = /*@__PURE__*/ createComponent<KiCheckboxElement, KiCheckboxEvents, Components.KiCheckbox>({
    tagName: 'ki-checkbox',
    elementClass: KiCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiCheckboxEvents,
    defineCustomElement: defineKiCheckbox
});
