'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiCard as KiCardElement, defineCustomElement as defineKiCard } from "@kimen/elements/components/ki-card.js";

export type KiCardEvents = NonNullable<unknown>;

export const KiCard: StencilReactComponent<KiCardElement, KiCardEvents, Components.KiCard> = /*@__PURE__*/ createComponent<KiCardElement, KiCardEvents, Components.KiCard>({
    tagName: 'ki-card',
    elementClass: KiCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiCardEvents,
    defineCustomElement: defineKiCard
});
