'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type KiDialogCloseDetail, type KiDialogCustomEvent } from "@kimen/elements";
import type { Components } from "@kimen/elements/components";
import { KiDialog as KiDialogElement, defineCustomElement as defineKiDialog } from "@kimen/elements/components/ki-dialog.js";

export type KiDialogEvents = { onKiClose: EventName<KiDialogCustomEvent<KiDialogCloseDetail>> };

export const KiDialog: StencilReactComponent<KiDialogElement, KiDialogEvents, Components.KiDialog> = /*@__PURE__*/ createComponent<KiDialogElement, KiDialogEvents, Components.KiDialog>({
    tagName: 'ki-dialog',
    elementClass: KiDialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onKiClose: 'ki-close' } as KiDialogEvents,
    defineCustomElement: defineKiDialog
});
