'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiDivider as KiDividerElement, defineCustomElement as defineKiDivider } from "@kimen/elements/components/ki-divider.js";

export type KiDividerEvents = NonNullable<unknown>;

export const KiDivider: StencilReactComponent<KiDividerElement, KiDividerEvents, Components.KiDivider> = /*@__PURE__*/ createComponent<KiDividerElement, KiDividerEvents, Components.KiDivider>({
    tagName: 'ki-divider',
    elementClass: KiDividerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiDividerEvents,
    defineCustomElement: defineKiDivider
});
