'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiIconButton as KiIconButtonElement, defineCustomElement as defineKiIconButton } from "@kimen/elements/components/ki-icon-button.js";

export type KiIconButtonEvents = NonNullable<unknown>;

export const KiIconButton: StencilReactComponent<KiIconButtonElement, KiIconButtonEvents, Components.KiIconButton> = /*@__PURE__*/ createComponent<KiIconButtonElement, KiIconButtonEvents, Components.KiIconButton>({
    tagName: 'ki-icon-button',
    elementClass: KiIconButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiIconButtonEvents,
    defineCustomElement: defineKiIconButton
});
