'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiInput as KiInputElement, defineCustomElement as defineKiInput } from "@kimen/elements/components/ki-input.js";

export type KiInputEvents = NonNullable<unknown>;

export const KiInput: StencilReactComponent<KiInputElement, KiInputEvents, Components.KiInput> = /*@__PURE__*/ createComponent<KiInputElement, KiInputEvents, Components.KiInput>({
    tagName: 'ki-input',
    elementClass: KiInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiInputEvents,
    defineCustomElement: defineKiInput
});
