'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiIndicator as KiIndicatorElement, defineCustomElement as defineKiIndicator } from "@kimen/elements/components/ki-indicator.js";

export type KiIndicatorEvents = NonNullable<unknown>;

export const KiIndicator: StencilReactComponent<KiIndicatorElement, KiIndicatorEvents, Components.KiIndicator> = /*@__PURE__*/ createComponent<KiIndicatorElement, KiIndicatorEvents, Components.KiIndicator>({
    tagName: 'ki-indicator',
    elementClass: KiIndicatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiIndicatorEvents,
    defineCustomElement: defineKiIndicator
});
