'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiListItem as KiListItemElement, defineCustomElement as defineKiListItem } from "@kimen/elements/components/ki-list-item.js";

export type KiListItemEvents = NonNullable<unknown>;

export const KiListItem: StencilReactComponent<KiListItemElement, KiListItemEvents, Components.KiListItem> = /*@__PURE__*/ createComponent<KiListItemElement, KiListItemEvents, Components.KiListItem>({
    tagName: 'ki-list-item',
    elementClass: KiListItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiListItemEvents,
    defineCustomElement: defineKiListItem
});
