'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiList as KiListElement, defineCustomElement as defineKiList } from "@kimen/elements/components/ki-list.js";

export type KiListEvents = NonNullable<unknown>;

export const KiList: StencilReactComponent<KiListElement, KiListEvents, Components.KiList> = /*@__PURE__*/ createComponent<KiListElement, KiListEvents, Components.KiList>({
    tagName: 'ki-list',
    elementClass: KiListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiListEvents,
    defineCustomElement: defineKiList
});
