'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiOption as KiOptionElement, defineCustomElement as defineKiOption } from "@kimen/elements/components/ki-option.js";

export type KiOptionEvents = NonNullable<unknown>;

export const KiOption: StencilReactComponent<KiOptionElement, KiOptionEvents, Components.KiOption> = /*@__PURE__*/ createComponent<KiOptionElement, KiOptionEvents, Components.KiOption>({
    tagName: 'ki-option',
    elementClass: KiOptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiOptionEvents,
    defineCustomElement: defineKiOption
});
