'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiProgress as KiProgressElement, defineCustomElement as defineKiProgress } from "@kimen/elements/components/ki-progress.js";

export type KiProgressEvents = NonNullable<unknown>;

export const KiProgress: StencilReactComponent<KiProgressElement, KiProgressEvents, Components.KiProgress> = /*@__PURE__*/ createComponent<KiProgressElement, KiProgressEvents, Components.KiProgress>({
    tagName: 'ki-progress',
    elementClass: KiProgressElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiProgressEvents,
    defineCustomElement: defineKiProgress
});
