'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiQr as KiQrElement, defineCustomElement as defineKiQr } from "@kimen/elements/components/ki-qr.js";

export type KiQrEvents = NonNullable<unknown>;

export const KiQr: StencilReactComponent<KiQrElement, KiQrEvents, Components.KiQr> = /*@__PURE__*/ createComponent<KiQrElement, KiQrEvents, Components.KiQr>({
    tagName: 'ki-qr',
    elementClass: KiQrElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiQrEvents,
    defineCustomElement: defineKiQr
});
