'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiRadio as KiRadioElement, defineCustomElement as defineKiRadio } from "@kimen/elements/components/ki-radio.js";

export type KiRadioEvents = NonNullable<unknown>;

export const KiRadio: StencilReactComponent<KiRadioElement, KiRadioEvents, Components.KiRadio> = /*@__PURE__*/ createComponent<KiRadioElement, KiRadioEvents, Components.KiRadio>({
    tagName: 'ki-radio',
    elementClass: KiRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiRadioEvents,
    defineCustomElement: defineKiRadio
});
