'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiRadioGroup as KiRadioGroupElement, defineCustomElement as defineKiRadioGroup } from "@kimen/elements/components/ki-radio-group.js";

export type KiRadioGroupEvents = NonNullable<unknown>;

export const KiRadioGroup: StencilReactComponent<KiRadioGroupElement, KiRadioGroupEvents, Components.KiRadioGroup, 'label'> = /*@__PURE__*/ createComponent<KiRadioGroupElement, KiRadioGroupEvents, Components.KiRadioGroup, 'label'>({
    tagName: 'ki-radio-group',
    elementClass: KiRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiRadioGroupEvents,
    defineCustomElement: defineKiRadioGroup
});
