'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiScroller as KiScrollerElement, defineCustomElement as defineKiScroller } from "@kimen/elements/components/ki-scroller.js";

export type KiScrollerEvents = NonNullable<unknown>;

export const KiScroller: StencilReactComponent<KiScrollerElement, KiScrollerEvents, Components.KiScroller> = /*@__PURE__*/ createComponent<KiScrollerElement, KiScrollerEvents, Components.KiScroller>({
    tagName: 'ki-scroller',
    elementClass: KiScrollerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiScrollerEvents,
    defineCustomElement: defineKiScroller
});
