'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiSelect as KiSelectElement, defineCustomElement as defineKiSelect } from "@kimen/elements/components/ki-select.js";

export type KiSelectEvents = NonNullable<unknown>;

export const KiSelect: StencilReactComponent<KiSelectElement, KiSelectEvents, Components.KiSelect> = /*@__PURE__*/ createComponent<KiSelectElement, KiSelectEvents, Components.KiSelect>({
    tagName: 'ki-select',
    elementClass: KiSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiSelectEvents,
    defineCustomElement: defineKiSelect
});
