'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiStatus as KiStatusElement, defineCustomElement as defineKiStatus } from "@kimen/elements/components/ki-status.js";

export type KiStatusEvents = NonNullable<unknown>;

export const KiStatus: StencilReactComponent<KiStatusElement, KiStatusEvents, Components.KiStatus> = /*@__PURE__*/ createComponent<KiStatusElement, KiStatusEvents, Components.KiStatus>({
    tagName: 'ki-status',
    elementClass: KiStatusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiStatusEvents,
    defineCustomElement: defineKiStatus
});
