'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiSwitch as KiSwitchElement, defineCustomElement as defineKiSwitch } from "@kimen/elements/components/ki-switch.js";

export type KiSwitchEvents = NonNullable<unknown>;

export const KiSwitch: StencilReactComponent<KiSwitchElement, KiSwitchEvents, Components.KiSwitch> = /*@__PURE__*/ createComponent<KiSwitchElement, KiSwitchEvents, Components.KiSwitch>({
    tagName: 'ki-switch',
    elementClass: KiSwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiSwitchEvents,
    defineCustomElement: defineKiSwitch
});
