'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiTab as KiTabElement, defineCustomElement as defineKiTab } from "@kimen/elements/components/ki-tab.js";

export type KiTabEvents = NonNullable<unknown>;

export const KiTab: StencilReactComponent<KiTabElement, KiTabEvents, Components.KiTab> = /*@__PURE__*/ createComponent<KiTabElement, KiTabEvents, Components.KiTab>({
    tagName: 'ki-tab',
    elementClass: KiTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiTabEvents,
    defineCustomElement: defineKiTab
});
