'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiTooltip as KiTooltipElement, defineCustomElement as defineKiTooltip } from "@kimen/elements/components/ki-tooltip.js";

export type KiTooltipEvents = NonNullable<unknown>;

export const KiTooltip: StencilReactComponent<KiTooltipElement, KiTooltipEvents, Components.KiTooltip> = /*@__PURE__*/ createComponent<KiTooltipElement, KiTooltipEvents, Components.KiTooltip>({
    tagName: 'ki-tooltip',
    elementClass: KiTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiTooltipEvents,
    defineCustomElement: defineKiTooltip
});
