'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type KiTabsCustomEvent } from "@kimen/elements";
import type { Components } from "@kimen/elements/components";
import { KiTabs as KiTabsElement, defineCustomElement as defineKiTabs } from "@kimen/elements/components/ki-tabs.js";

export type KiTabsEvents = { onKiChange: EventName<KiTabsCustomEvent<{ value: string }>> };

export const KiTabs: StencilReactComponent<KiTabsElement, KiTabsEvents, Components.KiTabs> = /*@__PURE__*/ createComponent<KiTabsElement, KiTabsEvents, Components.KiTabs>({
    tagName: 'ki-tabs',
    elementClass: KiTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onKiChange: 'ki-change' } as KiTabsEvents,
    defineCustomElement: defineKiTabs
});
