'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiTabPanel as KiTabPanelElement, defineCustomElement as defineKiTabPanel } from "@kimen/elements/components/ki-tab-panel.js";

export type KiTabPanelEvents = NonNullable<unknown>;

export const KiTabPanel: StencilReactComponent<KiTabPanelElement, KiTabPanelEvents, Components.KiTabPanel> = /*@__PURE__*/ createComponent<KiTabPanelElement, KiTabPanelEvents, Components.KiTabPanel>({
    tagName: 'ki-tab-panel',
    elementClass: KiTabPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiTabPanelEvents,
    defineCustomElement: defineKiTabPanel
});
