'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiTextarea as KiTextareaElement, defineCustomElement as defineKiTextarea } from "@kimen/elements/components/ki-textarea.js";

export type KiTextareaEvents = NonNullable<unknown>;

export const KiTextarea: StencilReactComponent<KiTextareaElement, KiTextareaEvents, Components.KiTextarea, 'label'> = /*@__PURE__*/ createComponent<KiTextareaElement, KiTextareaEvents, Components.KiTextarea, 'label'>({
    tagName: 'ki-textarea',
    elementClass: KiTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiTextareaEvents,
    defineCustomElement: defineKiTextarea
});
