'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@kimen/elements/components";
import { KiVideo as KiVideoElement, defineCustomElement as defineKiVideo } from "@kimen/elements/components/ki-video.js";

export type KiVideoEvents = NonNullable<unknown>;

export const KiVideo: StencilReactComponent<KiVideoElement, KiVideoEvents, Components.KiVideo> = /*@__PURE__*/ createComponent<KiVideoElement, KiVideoEvents, Components.KiVideo>({
    tagName: 'ki-video',
    elementClass: KiVideoElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as KiVideoEvents,
    defineCustomElement: defineKiVideo
});
