// Generates the self-contained MCP Apps surface document (spec 030 FR-002/FR-007).
// esbuild bundles the in-document runtime (guarded renderer + bridge, zod
// inlined) into one inline <script>; the document declares a content policy
// with NO external origin. Deterministic: byte-identical regeneration keeps a
// host's cached audit valid (S2). No network, no Date/random — pure transform.
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(here, '..');
const entry = resolve(packageRoot, 'src/surface-runtime.ts');
const outFile = resolve(packageRoot, 'src/generated/surface-document.ts');

// TypeScript source uses `.js` import specifiers (verbatimModuleSyntax); map
// them back to their `.ts` sources so esbuild bundles from src directly (no
// dependency on tsc output, so this runs before the type build).
const tsExtensionPlugin = {
  name: 'ts-extension',
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^\.\.?\/.*\.js$/ }, (args) => {
      const candidate = resolve(args.resolveDir, args.path.replace(/\.js$/, '.ts'));
      return existsSync(candidate) ? { path: candidate } : undefined;
    });
  },
};

const result = await build({
  bundle: true,
  entryPoints: [entry],
  format: 'iife',
  legalComments: 'none',
  minify: true,
  platform: 'browser',
  plugins: [tsExtensionPlugin],
  target: 'es2022',
  write: false,
});

const [output] = result.outputFiles;
let script = output.text;

// The bundled validator (zod) carries inert JSON-Schema `$id` string constants
// (json-schema.org draft URIs). They are never fetched — no code path in the
// render pipeline reads them, and the document's CSP forbids all network — but
// neutralizing them keeps the packaged document auditably free of ANY external
// origin, so a host's self-containment audit (S2) sees zero external URLs.
script = script.replace(/https?:\/\/json-schema\.org[^"'`\s)]*/g, 'urn:kimen:inert-schema-id');

// A content policy that references no external origin: everything is inline,
// nothing is fetchable (defense in depth — safe even if the host does not
// enforce it, spec Assumptions).
const csp = [
  "default-src 'none'",
  "script-src 'unsafe-inline'",
  "style-src 'unsafe-inline'",
  'img-src data:',
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<title>Kimen surface</title>
<style>:root{color-scheme:light dark}body{margin:0}#kimen-surface{display:block}</style>
</head>
<body>
<div id="kimen-surface"></div>
<script>${script}</script>
</body>
</html>
`;

const module = `/**
 * GENERATED by scripts/generate-surface.mjs — do not edit.
 *
 * The self-contained MCP Apps surface document (spec 030): one HTML document
 * with the guarded renderer inlined and a content policy that references no
 * external origin. Regeneration is byte-identical (S2).
 */
export const SURFACE_DOCUMENT = ${JSON.stringify(html)};
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, module, 'utf8');

console.log(
  `adapter-mcp-apps: generated surface-document.ts (${(html.length / 1024).toFixed(0)} KiB document)`,
);
