/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { KiAlertTone } from "./components/ki-alert/ki-alert.tone";
import { KiButtonSize, KiButtonTone, KiButtonType, KiButtonVariant } from "./components/ki-button/ki-button";
export { KiAlertTone } from "./components/ki-alert/ki-alert.tone";
export { KiButtonSize, KiButtonTone, KiButtonType, KiButtonVariant } from "./components/ki-button/ki-button";
export namespace Components {
    /**
     * A persistent inline status message with token-backed tone semantics.
     * When to use: show a persistent inline message about the state of a page or
     * section, such as a failed save, completed operation, or service notice, that
     * remains until the condition is resolved or the person dismisses it. Express
     * severity with `tone`, never custom styling.
     * When NOT to use: transient confirmations that expire on their own belong to
     * the future `ki-toast`; tiny status descriptors attached to another element
     * belong to `ki-badge`; blocking decisions belong to `ki-dialog`; inline
     * field-level validation belongs to the form control.
     * Assistive technology note: alerts that must be announced should be inserted
     * dynamically, or re-shown by clearing `dismissed`; alerts present at initial
     * page load are exposed with their role but platform announcement is not
     * guaranteed.
     */
    interface KiAlert {
        /**
          * Accessible name for the dismiss button. Override for localization; the default English string is the component's only built-in user-visible text.  When to use: provide a localized action name whenever the document language is not English. When NOT to use: do not put the alert message here; use the default slot.
          * @default 'Dismiss'
         */
        "dismissLabel": string;
        /**
          * Reflected dismissed state. User dismissal sets it; applications may also set or clear it. While true, the host remains in the document but renders no alert subtree and leaves the accessibility tree. Clearing it re-shows the alert and creates a dynamic live-region appearance.  When to use: persist or restore acknowledgement state from application data. When NOT to use: do not listen for programmatic changes as dismissal events; `ki-dismiss` is only for user activation.
          * @default false
         */
        "dismissed": boolean;
        /**
          * Renders one native dismiss button when true. The button sits outside the live-region boundary, so its accessible name is not announced as part of the alert message. When false, the alert adds no tab stop.  When to use: allow a person to acknowledge and clear a persistent message. When NOT to use: do not use dismissible for auto-expiring messages; that is future `ki-toast` behavior.
          * @default false
         */
        "dismissible": boolean;
        /**
          * Optional emphasized text rendered before the message inside the live region. Empty strings render no heading. The heading is a `strong` element, not a document heading, so it never changes page outline.  When to use: add a short label when it helps identify the status message. When NOT to use: do not use heading for page structure; use a real heading outside the alert when the document needs one.
         */
        "heading"?: string;
        /**
          * Semantic intent for visual styling and live-region urgency. `danger` and `warning` expose `role="alert"`; `neutral`, `success`, `info`, absent, and unrecognized values expose `role="status"`. Unknown values keep rendering and fall back to the neutral token matrix by CSS construction.  When to use: choose the tone that describes the page or section state. When NOT to use: do not use tone for layout, density, or filled-vs-outlined styling; those are token/theme decisions.
          * @default 'neutral'
         */
        "tone": KiAlertTone | (string & {});
    }
    /**
     * A token-styled action button with native button semantics.
     * When to use: trigger the single main action of a view, supporting actions
     * in descending hierarchy, or confirming/destructive actions through tone.
     * When NOT to use: navigation, icon-only actions, persistent toggles, or
     * loading/progress semantics.
     */
    interface KiButton {
        /**
          * Prevents activation, removes the button from keyboard reach, and exposes the unavailable state through the internal native button. When NOT to use: do not use disabled for pending/loading semantics.
          * @default false
         */
        "disabled": boolean;
        /**
          * Form-data key contributed when this button submits its form. When NOT to use: omit when no submitter value should be sent.
         */
        "name"?: string;
        /**
          * Token-backed button size. Every size keeps at least the minimum pointer target; choose the size that matches the density of the surrounding UI. When NOT to use: do not use `ki-button` for icon-only compact controls.
          * @default 'md'
         */
        "size": KiButtonSize;
        /**
          * Semantic intent for the action, independent of hierarchy. Use `success` for confirming actions and `danger` for destructive actions. When NOT to use: do not use tone for visual hierarchy; use `variant`.
          * @default 'neutral'
         */
        "tone": KiButtonTone;
        /**
          * Native form action type: `submit` submits the owning form (running constraint validation and contributing `name`/`value` to the form data), `reset` restores field defaults, `button` never touches the form. Cancel a submission from the form's `submit` event (`preventDefault()`); unlike a native button, `preventDefault()` on the `click` event does not cancel it. During submission `event.submitter` is a transient native button carrying this element's `name`/`value`, not the `ki-button` host. When NOT to use: use `button` when the action must never submit a form.
          * @default 'submit'
         */
        "type": KiButtonType;
        /**
          * Form-data value paired with `name` when this button submits its form. When NOT to use: omit when the default empty submitter value is intended.
         */
        "value"?: string;
        /**
          * Visual hierarchy for the action. Use `primary` for the single main action in a view and lower-emphasis variants for supporting actions. When NOT to use: do not use variant to signal success or danger; use `tone` for intent.
          * @default 'secondary'
         */
        "variant": KiButtonVariant;
    }
}
export interface KiAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKiAlertElement;
}
declare global {
    interface HTMLKiAlertElementEventMap {
        "ki-dismiss": null;
    }
    /**
     * A persistent inline status message with token-backed tone semantics.
     * When to use: show a persistent inline message about the state of a page or
     * section, such as a failed save, completed operation, or service notice, that
     * remains until the condition is resolved or the person dismisses it. Express
     * severity with `tone`, never custom styling.
     * When NOT to use: transient confirmations that expire on their own belong to
     * the future `ki-toast`; tiny status descriptors attached to another element
     * belong to `ki-badge`; blocking decisions belong to `ki-dialog`; inline
     * field-level validation belongs to the form control.
     * Assistive technology note: alerts that must be announced should be inserted
     * dynamically, or re-shown by clearing `dismissed`; alerts present at initial
     * page load are exposed with their role but platform announcement is not
     * guaranteed.
     */
    interface HTMLKiAlertElement extends Components.KiAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKiAlertElementEventMap>(type: K, listener: (this: HTMLKiAlertElement, ev: KiAlertCustomEvent<HTMLKiAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKiAlertElementEventMap>(type: K, listener: (this: HTMLKiAlertElement, ev: KiAlertCustomEvent<HTMLKiAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKiAlertElement: {
        prototype: HTMLKiAlertElement;
        new (): HTMLKiAlertElement;
    };
    /**
     * A token-styled action button with native button semantics.
     * When to use: trigger the single main action of a view, supporting actions
     * in descending hierarchy, or confirming/destructive actions through tone.
     * When NOT to use: navigation, icon-only actions, persistent toggles, or
     * loading/progress semantics.
     */
    interface HTMLKiButtonElement extends Components.KiButton, HTMLStencilElement {
    }
    var HTMLKiButtonElement: {
        prototype: HTMLKiButtonElement;
        new (): HTMLKiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ki-alert": HTMLKiAlertElement;
        "ki-button": HTMLKiButtonElement;
    }
}
declare namespace LocalJSX {
    /**
     * A persistent inline status message with token-backed tone semantics.
     * When to use: show a persistent inline message about the state of a page or
     * section, such as a failed save, completed operation, or service notice, that
     * remains until the condition is resolved or the person dismisses it. Express
     * severity with `tone`, never custom styling.
     * When NOT to use: transient confirmations that expire on their own belong to
     * the future `ki-toast`; tiny status descriptors attached to another element
     * belong to `ki-badge`; blocking decisions belong to `ki-dialog`; inline
     * field-level validation belongs to the form control.
     * Assistive technology note: alerts that must be announced should be inserted
     * dynamically, or re-shown by clearing `dismissed`; alerts present at initial
     * page load are exposed with their role but platform announcement is not
     * guaranteed.
     */
    interface KiAlert {
        /**
          * Accessible name for the dismiss button. Override for localization; the default English string is the component's only built-in user-visible text.  When to use: provide a localized action name whenever the document language is not English. When NOT to use: do not put the alert message here; use the default slot.
          * @default 'Dismiss'
         */
        "dismissLabel"?: string;
        /**
          * Reflected dismissed state. User dismissal sets it; applications may also set or clear it. While true, the host remains in the document but renders no alert subtree and leaves the accessibility tree. Clearing it re-shows the alert and creates a dynamic live-region appearance.  When to use: persist or restore acknowledgement state from application data. When NOT to use: do not listen for programmatic changes as dismissal events; `ki-dismiss` is only for user activation.
          * @default false
         */
        "dismissed"?: boolean;
        /**
          * Renders one native dismiss button when true. The button sits outside the live-region boundary, so its accessible name is not announced as part of the alert message. When false, the alert adds no tab stop.  When to use: allow a person to acknowledge and clear a persistent message. When NOT to use: do not use dismissible for auto-expiring messages; that is future `ki-toast` behavior.
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * Optional emphasized text rendered before the message inside the live region. Empty strings render no heading. The heading is a `strong` element, not a document heading, so it never changes page outline.  When to use: add a short label when it helps identify the status message. When NOT to use: do not use heading for page structure; use a real heading outside the alert when the document needs one.
         */
        "heading"?: string;
        "onKi-dismiss"?: (event: KiAlertCustomEvent<null>) => void;
        /**
          * Semantic intent for visual styling and live-region urgency. `danger` and `warning` expose `role="alert"`; `neutral`, `success`, `info`, absent, and unrecognized values expose `role="status"`. Unknown values keep rendering and fall back to the neutral token matrix by CSS construction.  When to use: choose the tone that describes the page or section state. When NOT to use: do not use tone for layout, density, or filled-vs-outlined styling; those are token/theme decisions.
          * @default 'neutral'
         */
        "tone"?: KiAlertTone | (string & {});
    }
    /**
     * A token-styled action button with native button semantics.
     * When to use: trigger the single main action of a view, supporting actions
     * in descending hierarchy, or confirming/destructive actions through tone.
     * When NOT to use: navigation, icon-only actions, persistent toggles, or
     * loading/progress semantics.
     */
    interface KiButton {
        /**
          * Prevents activation, removes the button from keyboard reach, and exposes the unavailable state through the internal native button. When NOT to use: do not use disabled for pending/loading semantics.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Form-data key contributed when this button submits its form. When NOT to use: omit when no submitter value should be sent.
         */
        "name"?: string;
        /**
          * Token-backed button size. Every size keeps at least the minimum pointer target; choose the size that matches the density of the surrounding UI. When NOT to use: do not use `ki-button` for icon-only compact controls.
          * @default 'md'
         */
        "size"?: KiButtonSize;
        /**
          * Semantic intent for the action, independent of hierarchy. Use `success` for confirming actions and `danger` for destructive actions. When NOT to use: do not use tone for visual hierarchy; use `variant`.
          * @default 'neutral'
         */
        "tone"?: KiButtonTone;
        /**
          * Native form action type: `submit` submits the owning form (running constraint validation and contributing `name`/`value` to the form data), `reset` restores field defaults, `button` never touches the form. Cancel a submission from the form's `submit` event (`preventDefault()`); unlike a native button, `preventDefault()` on the `click` event does not cancel it. During submission `event.submitter` is a transient native button carrying this element's `name`/`value`, not the `ki-button` host. When NOT to use: use `button` when the action must never submit a form.
          * @default 'submit'
         */
        "type"?: KiButtonType;
        /**
          * Form-data value paired with `name` when this button submits its form. When NOT to use: omit when the default empty submitter value is intended.
         */
        "value"?: string;
        /**
          * Visual hierarchy for the action. Use `primary` for the single main action in a view and lower-emphasis variants for supporting actions. When NOT to use: do not use variant to signal success or danger; use `tone` for intent.
          * @default 'secondary'
         */
        "variant"?: KiButtonVariant;
    }

    interface KiAlertAttributes {
        "tone": KiAlertTone | (string & {});
        "heading": string;
        "dismissible": boolean;
        "dismissLabel": string;
        "dismissed": boolean;
    }
    interface KiButtonAttributes {
        "variant": KiButtonVariant;
        "tone": KiButtonTone;
        "size": KiButtonSize;
        "type": KiButtonType;
        "name": string;
        "value": string;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "ki-alert": Omit<KiAlert, keyof KiAlertAttributes> & { [K in keyof KiAlert & keyof KiAlertAttributes]?: KiAlert[K] } & { [K in keyof KiAlert & keyof KiAlertAttributes as `attr:${K}`]?: KiAlertAttributes[K] } & { [K in keyof KiAlert & keyof KiAlertAttributes as `prop:${K}`]?: KiAlert[K] };
        "ki-button": Omit<KiButton, keyof KiButtonAttributes> & { [K in keyof KiButton & keyof KiButtonAttributes]?: KiButton[K] } & { [K in keyof KiButton & keyof KiButtonAttributes as `attr:${K}`]?: KiButtonAttributes[K] } & { [K in keyof KiButton & keyof KiButtonAttributes as `prop:${K}`]?: KiButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A persistent inline status message with token-backed tone semantics.
             * When to use: show a persistent inline message about the state of a page or
             * section, such as a failed save, completed operation, or service notice, that
             * remains until the condition is resolved or the person dismisses it. Express
             * severity with `tone`, never custom styling.
             * When NOT to use: transient confirmations that expire on their own belong to
             * the future `ki-toast`; tiny status descriptors attached to another element
             * belong to `ki-badge`; blocking decisions belong to `ki-dialog`; inline
             * field-level validation belongs to the form control.
             * Assistive technology note: alerts that must be announced should be inserted
             * dynamically, or re-shown by clearing `dismissed`; alerts present at initial
             * page load are exposed with their role but platform announcement is not
             * guaranteed.
             */
            "ki-alert": LocalJSX.IntrinsicElements["ki-alert"] & JSXBase.HTMLAttributes<HTMLKiAlertElement>;
            /**
             * A token-styled action button with native button semantics.
             * When to use: trigger the single main action of a view, supporting actions
             * in descending hierarchy, or confirming/destructive actions through tone.
             * When NOT to use: navigation, icon-only actions, persistent toggles, or
             * loading/progress semantics.
             */
            "ki-button": LocalJSX.IntrinsicElements["ki-button"] & JSXBase.HTMLAttributes<HTMLKiButtonElement>;
        }
    }
}
