/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  /**
   * Factory smoke-test component. Proves the Fase 0 gate wiring end to end and
   * is deleted when the first real component lands (see docs/roadmap.md).
   * When to use: never in production. When NOT to use: always in production.
   */
  interface KiHello {
    /**
     * Name to greet.
     * @default 'Kimen'
     */
    name: string;
  }
}
declare global {
  /**
   * Factory smoke-test component. Proves the Fase 0 gate wiring end to end and
   * is deleted when the first real component lands (see docs/roadmap.md).
   * When to use: never in production. When NOT to use: always in production.
   */
  interface HTMLKiHelloElement extends Components.KiHello, HTMLStencilElement {}
  var HTMLKiHelloElement: {
    prototype: HTMLKiHelloElement;
    new (): HTMLKiHelloElement;
  };
  interface HTMLElementTagNameMap {
    'ki-hello': HTMLKiHelloElement;
  }
}
declare namespace LocalJSX {
  /**
   * Factory smoke-test component. Proves the Fase 0 gate wiring end to end and
   * is deleted when the first real component lands (see docs/roadmap.md).
   * When to use: never in production. When NOT to use: always in production.
   */
  interface KiHello {
    /**
     * Name to greet.
     * @default 'Kimen'
     */
    name?: string;
  }

  interface KiHelloAttributes {
    name: string;
  }

  interface IntrinsicElements {
    'ki-hello': Omit<KiHello, keyof KiHelloAttributes> & {
      [K in keyof KiHello & keyof KiHelloAttributes]?: KiHello[K];
    } & { [K in keyof KiHello & keyof KiHelloAttributes as `attr:${K}`]?: KiHelloAttributes[K] } & {
      [K in keyof KiHello & keyof KiHelloAttributes as `prop:${K}`]?: KiHello[K];
    };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * Factory smoke-test component. Proves the Fase 0 gate wiring end to end and
       * is deleted when the first real component lands (see docs/roadmap.md).
       * When to use: never in production. When NOT to use: always in production.
       */
      'ki-hello': LocalJSX.IntrinsicElements['ki-hello'] &
        JSXBase.HTMLAttributes<HTMLKiHelloElement>;
    }
  }
}
