/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { KiButtonSize, KiButtonTone, KiButtonType, KiButtonVariant } from "./components/ki-button/ki-button";
import { KiProgressShape } from "./components/ki-progress/ki-progress.math";
export { KiButtonSize, KiButtonTone, KiButtonType, KiButtonVariant } from "./components/ki-button/ki-button";
export { KiProgressShape } from "./components/ki-progress/ki-progress.math";
export namespace Components {
    /**
     * A token-styled action button with native button semantics.
     * When to use: trigger the single main action of a view, supporting actions
     * in descending hierarchy, or confirming/destructive actions through tone.
     * When NOT to use: navigation, icon-only actions, persistent toggles, or
     * loading/progress semantics.
     */
    interface KiButton {
        /**
          * Prevents activation, removes the button from keyboard reach, and exposes the unavailable state through the internal native button. When NOT to use: do not use disabled for pending/loading semantics.
          * @default false
         */
        "disabled": boolean;
        /**
          * Form-data key contributed when this button submits its form. When NOT to use: omit when no submitter value should be sent.
         */
        "name"?: string;
        /**
          * Token-backed button size. Every size keeps at least the minimum pointer target; choose the size that matches the density of the surrounding UI. When NOT to use: do not use `ki-button` for icon-only compact controls.
          * @default 'md'
         */
        "size": KiButtonSize;
        /**
          * Semantic intent for the action, independent of hierarchy. Use `success` for confirming actions and `danger` for destructive actions. When NOT to use: do not use tone for visual hierarchy; use `variant`.
          * @default 'neutral'
         */
        "tone": KiButtonTone;
        /**
          * Native form action type: `submit` submits the owning form (running constraint validation and contributing `name`/`value` to the form data), `reset` restores field defaults, `button` never touches the form. Cancel a submission from the form's `submit` event (`preventDefault()`); unlike a native button, `preventDefault()` on the `click` event does not cancel it. During submission `event.submitter` is a transient native button carrying this element's `name`/`value`, not the `ki-button` host. When NOT to use: use `button` when the action must never submit a form.
          * @default 'submit'
         */
        "type": KiButtonType;
        /**
          * Form-data value paired with `name` when this button submits its form. When NOT to use: omit when the default empty submitter value is intended.
         */
        "value"?: string;
        /**
          * Visual hierarchy for the action. Use `primary` for the single main action in a view and lower-emphasis variants for supporting actions. When NOT to use: do not use variant to signal success or danger; use `tone` for intent.
          * @default 'secondary'
         */
        "variant": KiButtonVariant;
    }
    /**
     * A token-styled, non-interactive progress indicator for known or unknown
     * duration work.
     * When to use: communicate advancement of an ongoing task such as upload,
     * download, installation or multi-step processing. Use `value`/`max` when
     * the completed fraction is known; use `indeterminate` when work is ongoing
     * but its duration cannot be measured, including loading-indicator use cases.
     * Choose `linear` in page flows and lists, and `circular` in compact or
     * centered placements. Always set `label` to what is progressing.
     * When NOT to use: static measurements within a known range such as disk
     * usage or scores (gauge/meter), step-by-step wizard navigation (stepper),
     * skeleton placeholders while content loads, or operations that finish in
     * under about one second.
     */
    interface KiProgress {
        /**
          * Unknown-duration mode. When set, no completed fraction or current value is exposed. Its motion is declared only when reduced motion is not requested. When to use: show ongoing work whose duration or total cannot be measured. When NOT to use: do not use for known fractions; use `value` and `max`.
          * @default false
         */
        "indeterminate": boolean;
        /**
          * Accessible name applied to the internal progressbar. Always set this to what is progressing, such as "Uploading report.pdf". Without it the element renders but exposes no accessible name. When NOT to use: do not use a generic label such as "Loading" when the task can be named more specifically.
         */
        "label"?: string;
        /**
          * Total amount. Non-finite, zero or negative values normalize to `100` for presentation and ARIA. When to use: set when a determinate task's total is not 100. When NOT to use: omit for conventional percentage-style progress.
          * @default 100
         */
        "max": number;
        /**
          * Structural presentation. Use `linear` in page flows and lists; use `circular` in compact or centered placements. Unknown values render linear. When NOT to use: do not use shape to encode semantic status or task intent.
          * @default 'linear'
         */
        "shape": KiProgressShape;
        /**
          * Completed amount. Presentation and ARIA clamp this value to `0..max`; malformed values fall back to `0`. Ignored while `indeterminate` is set. When to use: set with `max` for determinate task advancement. When NOT to use: do not set a fabricated value for unknown-duration work; set `indeterminate` instead.
          * @default 0
         */
        "value": number;
    }
}
declare global {
    /**
     * A token-styled action button with native button semantics.
     * When to use: trigger the single main action of a view, supporting actions
     * in descending hierarchy, or confirming/destructive actions through tone.
     * When NOT to use: navigation, icon-only actions, persistent toggles, or
     * loading/progress semantics.
     */
    interface HTMLKiButtonElement extends Components.KiButton, HTMLStencilElement {
    }
    var HTMLKiButtonElement: {
        prototype: HTMLKiButtonElement;
        new (): HTMLKiButtonElement;
    };
    /**
     * A token-styled, non-interactive progress indicator for known or unknown
     * duration work.
     * When to use: communicate advancement of an ongoing task such as upload,
     * download, installation or multi-step processing. Use `value`/`max` when
     * the completed fraction is known; use `indeterminate` when work is ongoing
     * but its duration cannot be measured, including loading-indicator use cases.
     * Choose `linear` in page flows and lists, and `circular` in compact or
     * centered placements. Always set `label` to what is progressing.
     * When NOT to use: static measurements within a known range such as disk
     * usage or scores (gauge/meter), step-by-step wizard navigation (stepper),
     * skeleton placeholders while content loads, or operations that finish in
     * under about one second.
     */
    interface HTMLKiProgressElement extends Components.KiProgress, HTMLStencilElement {
    }
    var HTMLKiProgressElement: {
        prototype: HTMLKiProgressElement;
        new (): HTMLKiProgressElement;
    };
    interface HTMLElementTagNameMap {
        "ki-button": HTMLKiButtonElement;
        "ki-progress": HTMLKiProgressElement;
    }
}
declare namespace LocalJSX {
    /**
     * A token-styled action button with native button semantics.
     * When to use: trigger the single main action of a view, supporting actions
     * in descending hierarchy, or confirming/destructive actions through tone.
     * When NOT to use: navigation, icon-only actions, persistent toggles, or
     * loading/progress semantics.
     */
    interface KiButton {
        /**
          * Prevents activation, removes the button from keyboard reach, and exposes the unavailable state through the internal native button. When NOT to use: do not use disabled for pending/loading semantics.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Form-data key contributed when this button submits its form. When NOT to use: omit when no submitter value should be sent.
         */
        "name"?: string;
        /**
          * Token-backed button size. Every size keeps at least the minimum pointer target; choose the size that matches the density of the surrounding UI. When NOT to use: do not use `ki-button` for icon-only compact controls.
          * @default 'md'
         */
        "size"?: KiButtonSize;
        /**
          * Semantic intent for the action, independent of hierarchy. Use `success` for confirming actions and `danger` for destructive actions. When NOT to use: do not use tone for visual hierarchy; use `variant`.
          * @default 'neutral'
         */
        "tone"?: KiButtonTone;
        /**
          * Native form action type: `submit` submits the owning form (running constraint validation and contributing `name`/`value` to the form data), `reset` restores field defaults, `button` never touches the form. Cancel a submission from the form's `submit` event (`preventDefault()`); unlike a native button, `preventDefault()` on the `click` event does not cancel it. During submission `event.submitter` is a transient native button carrying this element's `name`/`value`, not the `ki-button` host. When NOT to use: use `button` when the action must never submit a form.
          * @default 'submit'
         */
        "type"?: KiButtonType;
        /**
          * Form-data value paired with `name` when this button submits its form. When NOT to use: omit when the default empty submitter value is intended.
         */
        "value"?: string;
        /**
          * Visual hierarchy for the action. Use `primary` for the single main action in a view and lower-emphasis variants for supporting actions. When NOT to use: do not use variant to signal success or danger; use `tone` for intent.
          * @default 'secondary'
         */
        "variant"?: KiButtonVariant;
    }
    /**
     * A token-styled, non-interactive progress indicator for known or unknown
     * duration work.
     * When to use: communicate advancement of an ongoing task such as upload,
     * download, installation or multi-step processing. Use `value`/`max` when
     * the completed fraction is known; use `indeterminate` when work is ongoing
     * but its duration cannot be measured, including loading-indicator use cases.
     * Choose `linear` in page flows and lists, and `circular` in compact or
     * centered placements. Always set `label` to what is progressing.
     * When NOT to use: static measurements within a known range such as disk
     * usage or scores (gauge/meter), step-by-step wizard navigation (stepper),
     * skeleton placeholders while content loads, or operations that finish in
     * under about one second.
     */
    interface KiProgress {
        /**
          * Unknown-duration mode. When set, no completed fraction or current value is exposed. Its motion is declared only when reduced motion is not requested. When to use: show ongoing work whose duration or total cannot be measured. When NOT to use: do not use for known fractions; use `value` and `max`.
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * Accessible name applied to the internal progressbar. Always set this to what is progressing, such as "Uploading report.pdf". Without it the element renders but exposes no accessible name. When NOT to use: do not use a generic label such as "Loading" when the task can be named more specifically.
         */
        "label"?: string;
        /**
          * Total amount. Non-finite, zero or negative values normalize to `100` for presentation and ARIA. When to use: set when a determinate task's total is not 100. When NOT to use: omit for conventional percentage-style progress.
          * @default 100
         */
        "max"?: number;
        /**
          * Structural presentation. Use `linear` in page flows and lists; use `circular` in compact or centered placements. Unknown values render linear. When NOT to use: do not use shape to encode semantic status or task intent.
          * @default 'linear'
         */
        "shape"?: KiProgressShape;
        /**
          * Completed amount. Presentation and ARIA clamp this value to `0..max`; malformed values fall back to `0`. Ignored while `indeterminate` is set. When to use: set with `max` for determinate task advancement. When NOT to use: do not set a fabricated value for unknown-duration work; set `indeterminate` instead.
          * @default 0
         */
        "value"?: number;
    }

    interface KiButtonAttributes {
        "variant": KiButtonVariant;
        "tone": KiButtonTone;
        "size": KiButtonSize;
        "type": KiButtonType;
        "name": string;
        "value": string;
        "disabled": boolean;
    }
    interface KiProgressAttributes {
        "value": number;
        "max": number;
        "indeterminate": boolean;
        "shape": KiProgressShape;
        "label": string;
    }

    interface IntrinsicElements {
        "ki-button": Omit<KiButton, keyof KiButtonAttributes> & { [K in keyof KiButton & keyof KiButtonAttributes]?: KiButton[K] } & { [K in keyof KiButton & keyof KiButtonAttributes as `attr:${K}`]?: KiButtonAttributes[K] } & { [K in keyof KiButton & keyof KiButtonAttributes as `prop:${K}`]?: KiButton[K] };
        "ki-progress": Omit<KiProgress, keyof KiProgressAttributes> & { [K in keyof KiProgress & keyof KiProgressAttributes]?: KiProgress[K] } & { [K in keyof KiProgress & keyof KiProgressAttributes as `attr:${K}`]?: KiProgressAttributes[K] } & { [K in keyof KiProgress & keyof KiProgressAttributes as `prop:${K}`]?: KiProgress[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A token-styled action button with native button semantics.
             * When to use: trigger the single main action of a view, supporting actions
             * in descending hierarchy, or confirming/destructive actions through tone.
             * When NOT to use: navigation, icon-only actions, persistent toggles, or
             * loading/progress semantics.
             */
            "ki-button": LocalJSX.IntrinsicElements["ki-button"] & JSXBase.HTMLAttributes<HTMLKiButtonElement>;
            /**
             * A token-styled, non-interactive progress indicator for known or unknown
             * duration work.
             * When to use: communicate advancement of an ongoing task such as upload,
             * download, installation or multi-step processing. Use `value`/`max` when
             * the completed fraction is known; use `indeterminate` when work is ongoing
             * but its duration cannot be measured, including loading-indicator use cases.
             * Choose `linear` in page flows and lists, and `circular` in compact or
             * centered placements. Always set `label` to what is progressing.
             * When NOT to use: static measurements within a known range such as disk
             * usage or scores (gauge/meter), step-by-step wizard navigation (stepper),
             * skeleton placeholders while content loads, or operations that finish in
             * under about one second.
             */
            "ki-progress": LocalJSX.IntrinsicElements["ki-progress"] & JSXBase.HTMLAttributes<HTMLKiProgressElement>;
        }
    }
}
